pushed tags to wholmgren, retesting

diff --git a/.github/workflows/publish-to-pypi-testpypi.yml b/.github/workflows/publish-to-pypi-testpypi.yml
--- a/.github/workflows/publish-to-pypi-testpypi.yml
+++ b/.github/workflows/publish-to-pypi-testpypi.yml
@@ -9,10 +9,12 @@ jobs:
     steps:
     # fetch all commits and tags so versioneer works
     - uses: actions/checkout@v2
-    - run: |
-        git fetch --prune --unshallow --tags
-        echo exit code $?
-        git tag --list
+      with:
+        fetch-depth: 0
+    # - run: |
+    #     git fetch --prune --unshallow --tags
+    #     echo exit code $?
+    #     git tag --list
 
     - name: Set up Python
       uses: actions/setup-python@v2
@@ -24,8 +26,8 @@ jobs:
         python -m pip install --upgrade pip
         python -m pip install --upgrade setuptools wheel
 
-    - name: Install pvlib without dependencies for versioning only
-      run: pip install -e . --no-deps
+    # - name: Install pvlib without dependencies for versioning only
+    #   run: pip install -e . --no-deps
 
     - name: Build packages
       run: python setup.py sdist bdist_wheel
